<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    protected $guarded = [];

    public function translations(){
        return $this->hasMany(Translation::class);
    }

    public function parents(){
        return $this->hasMany(Attribute::class,'category_id');
    }

    public function translation(){
        return $this->hasOne(Translation::class)->whereLocale(session('lang'));
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($attribute){
            if($attribute->parents())
                $attribute->parents()->delete();
        });
    }
}
