<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
   protected $guarded = ['id'];

    public function getAvatarAttribute(){
        return 'https://www.gravatar.com/avatar/'.md5(strtolower($this->email ?? $this->note)).'.jpg?s=200&d=identicon';
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replys(){
        return $this->hasMany(Contact::class,'rep_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function($contact){
            $contact->replys()->delete();
        });
    }
}
