<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lang extends Model
{
    protected $table = "langs";

    protected $guarded = ['id'];

    public function post_lang(){
        return $this->belongsTo(PostLang::class,'value','lang');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($lang){
            if($lang->status == 1){
                $status = Lang::whereStatus(0)->first();
                $status->update(['status' => 1]);
                session()->put('lang', $status->value);
            }
        });
    }

}
