<?php

namespace App\Models;

use App\Enums\ProductSessionType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Cart;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Spatie\Activitylog\Traits\LogsActivity;

class Order extends Model
{
    use LogsActivity;

    protected static $logUnguarded = true;
    protected static $submitEmptyLogs = false;
    protected static $logOnlyDirty = true;

    protected $guarded = [];

    protected $casts = [
        'content' => 'array'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function product(){
        return $this->belongsTo(Product::class);
    }

//    public function getAmountAttribute(){
//
//        $amount = 0;
//        foreach (json_decode($this->content) as $item){
//            $amount += $item->qty;
//        }
//        return $amount;
//    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

//        static::saved(function($order){
//            $carts = Cart::content();
//
//            foreach($carts as $cart){
//                $order->sessions->product_id = $cart->id;
//                $order->sessions->amount = $cart->qty;
//                $order->sessions->rate = $cart->option->rate;
//                $order->sessions->vnd = $cart->price;
//                $order->sessions->total = $cart->option->price * $cart->qty;
//                $order->sessions->save();
//            }
//
//            Cart::destroy();
//        });
    }
}
