<?php

namespace App\Models;

use App\Enums\ActiveDisable;
use App\Enums\MediaType;
use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $guarded = [];

    public function scopePublic($q){
        $q->wherePublic(ActiveDisable::active);
    }

    public function scopeWithLocale($q){
        return $q->whereLang(session('lang'));
    }

    public function getThumbAttribute(){

        return resize_image($this->image);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function($photo){
            $photo->admin_id = $photo->admin_id ?? auth()->id();
        });
    }
}
