<?php

namespace App\Models;

use App\Enums\ActiveDisable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\Activitylog\Traits\LogsActivity;

class Translation extends Model
{
    use HasFactory, LogsActivity;

    protected static $logUnguarded = true;
    protected static $submitEmptyLogs = false;
    protected static $logOnlyDirty = true;

    protected $guarded = [];

    public $timestamps = false;

    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function post(){
       return $this->belongsTo(Post::class);
    }

    public function product(){
       return  $this->belongsTo(Product::class);
    }

    public function category(){
        return  $this->belongsTo(Category::class);
    }

    public function language(){
        return $this->belongsTo(Language::class,'locale','value');
    }

    public function getItemCategoryAttribute(){
        return $this->item->category->id ?? 0;
    }

    public function getItemAttribute(){
        if($this->post_id)
            return $this->post;

        if($this->product_id)
            return  $this->product;

        if($this->category_id)
            return  $this->category;
    }

    public function scopeLocale($q){
        return $q->whereLocale(session('lang'));
    }

    public function scopeOfSlug($q, $slug){
        return $q->whereSlug($slug);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

         static::saving(function($translation){

             $translation->title_seo = $translation->title_seo ?? $translation->name;
             $translation->description_seo = $translation->description_seo ?? $translation->name;

         });


    }
}
